### ISSUE TITLE
[Crash Bug] Crash when add single word mention with prefix "@".

### ISSUE THREAD

**Issue by kokitang** [szweier/SZMentionsSwift#86] opened 2018-09-26 06:32 UTC
How to reproduce:

1. Try on sample project (or any project)
2. If using sample project, change the dataSource to 

`private let mentions: [ExampleMention] = {
        return [
            "Steven",
            "John Smith",
            "Joe Tesla"].map {
                ExampleMention(name: $0, range: NSRange(location: 0, length: 0))
        }
    }()`

`func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let memtion = ExampleMention(name: "@" + mentionsList[indexPath.row].name, range: NSRange(location: 0, length: 0))
        listener.addMention(memtion)
    }`

3. In the textfield type "@Stev", click Steven.
4. Delete last "en ". Remains "@Stev". Mention tableView reappears.
5. Click John Smith.
6. Crash.

**Comment by kokitang** [comment] 2018-09-27 08:27
Temp fixed after hours of review codes. May have potential bug.

In `@discardableResult private func shouldAdjust(_ textView: UITextView, range: NSRange, text: String) -> Bool`

Change 
```
if let editedMention = mentions.mentionBeingEdited(at: range) {
            clearMention(editedMention)

            shouldAdjust = handleEditingMention(editedMention, textView: textView, range: range, text: text)
        }
```

To

```
if let editedMention = mentions.mentionBeingEdited(at: range) {
            clearMention(editedMention)
            editingMention = false
            shouldAdjust = handleEditingMention(editedMention, textView: textView, range: range, text: text)
        }
```

due to `clearMention(editedMention)` will reset `editingMention`, which makes `currentMentionRange` not updated at the first delete character inside mention.

e.g.
`currentMentionRange` not updated when
`@Steven` delete last `n`

**Comment by szweier** [comment] 2018-10-12 22:33
@kokitang I just tried the steps mentioned in your initial comment and I don't see how you are clicking `John Smith` when the text is `@ste` as this would filter the options list and only show Steven

**Comment by szweier** [comment] 2018-12-07 15:59
I'm still unable to reproduce this crash by using the steps provided in your first comment. Did you change anything else in the example? It seems strange that the string "Ste" would give you a tableview with "John Smith" as an option. Feel free to reopen this issue if you have more data to provide that may help me reproduce the bug. For now, I'm going to close it.

**Closed by szweier** 2018-12-07 15:59 UTC
